### ISSUE TITLE
Combining textRight with Col and className removes the col classes.

### ISSUE THREAD

**Issue by amaschas** [rbalicki2/react-bootstrap-extended#2]
When I attempt to use:

` <Col sm={6} className={'customClass} textRight>`

The resulting markup is:

`<div class='customClass text-right'>`

For some reason, the `col-sm-6` class is omitted.

**Comment by rbalicki2** [comment]
Thank you for finding this! I'm investigating and should have a solution soon.

**Comment by rbalicki2** [comment]
Awesome! It should be fixed in the latest master + latest npm version. There's also a test case. Thanks for finding this.
